### ISSUE TITLE
Chrome version not updated

### ISSUE THREAD

**Issue by eranlesser** [percy/example-percy-nightwatch#49]
Hi ,

I am getting :
 Error: An error occurred while retrieving a new session: "session not created: Chrome version must be between 71 and 75"

(my chrome version is 77)

**Comment by Robdel12** [comment]
Super old issue (sorry about that). Chromedriver is annoying since it requires lockstep to the version of the browser. With #82 we dropped chrome for firefox (which doesn't require any version lockstepping)
