### ISSUE TITLE
Error while trying to load the file percy-agent.js: window is not defined

### ISSUE THREAD

**Issue by olgamicollier** [percy/example-percy-nightwatch#68]
Hello! I'm having an error on running nightwatch.js tests with percy. Do you have any idea how to solve it?

![Screenshot at Jul 27 17-29-05](https://user-images.githubusercontent.com/62062574/88560642-b3182b00-d02e-11ea-9a97-de991fd2fc9c.png)

**Comment by Robdel12** [comment]
Hey @olgamicollier! Would you be able to give more context about what's going on? Is this happening within this example app? The file path in the screenshot suggests its not. 

The error here is saying here's no `window` object available in the browser -- what is the page / URL you're visiting and trying to snapshot? Is JS disabled?

**Comment by olgamicollier** [comment]
Hello Robert!

I've also tried to run the test with percy within the example app and having the same issue.

so without percy tests are passing
![Screenshot at Jul 28 13-06-51](https://user-images.githubusercontent.com/62062574/88658147-473bce00-d0d3-11ea-820e-c4be266a1da8.png)

with percy there is an error:
![Screenshot at Jul 28 13-08-11](https://user-images.githubusercontent.com/62062574/88658242-676b8d00-d0d3-11ea-9f3f-2f4e643ac17d.png)

My config file:
```javascript
const chromedriver = require('chromedriver')
const seleniumServer = require('selenium-server')
const percy = require('@percy/nightwatch')

module.exports = {
  src_folders: ['tests'],
  output_folder: false,
  custom_commands_path: "./node_modules/@percy",

  selenium: {
    start_process: true,
    server_path: seleniumServer.path,
    log_path: false,
    cli_args: {
      'webdriver.chrome.driver': "./chromedriver_mac",
    },
  },

  test_settings: {
    default: {
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
        chromeOptions: {
          args: ['headless'],
          w3c: false
        },
      },
    },

    Chrome: {
      desiredCapabilities: {
        browserName: 'chrome',
        javascriptEnabled: true,
      },
    },
  },
}

```

**Comment by olgamicollier** [comment]
Not correct path to percySnapshot command in the config file.. @Robdel12 sorry to take your time and thank you for your response!
